
name: Deploy to Koyeb

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to Koyeb
        uses: koyeb/koyeb-deploy-action@v1
        with:
          token: \${{ secrets.KOYEB_TOKEN }}
