name: Deploy to Koyeb

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Koyeb Container Registry
      run: echo "${{ secrets.KOYEB_TOKEN }}" | docker login registry.koyeb.com -u ${{ secrets.KOYEB_USERNAME }} --password-stdin

    - name: Build and Push Docker Image
      run: |
        docker build -t registry.koyeb.com/${{ secrets.KOYEB_USERNAME }}/psbotz:latest .
        docker push registry.koyeb.com/${{ secrets.KOYEB_USERNAME }}/psbotz:latest
