name: Deploy to Koyeb

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Deploy to Koyeb
        uses: koyeb/koyeb-deploy-action@v1
        with:
          token: ${{ secrets.KOYEB_API_TOKEN }}
          app-name: psbotz-deal-bot
          service-name: telegram-deal-bot
