name: Deploy to Koyeb

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Deploy to Koyeb
        uses: koyeb/koyeb-deploy-github-action@v1
        with:
          service-name: amazon-deals-telegram-bot
          token: ${{ secrets.KOYEB_API_TOKEN }}
